# Generated by Django 2.2.5 on 2019-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
